---
excluded:
- Pods
- Baitoru/Framework
- Baitoru/Resources
- XCode
opt_in_rules:
- todo
- mark
- function_body_length
- line_length
- colon
- comma
- trailing_semicolon
- cyclomatic_complexity
- overridden_super_call
- force_cast
- force_try
- force_unwrapping
- empty_count
- operator_whitespace
- opening_brace
- closing_brace
- return_arrow_whitespace
- leading_whitespace
- trailing_newline
- statement_position
- vertical_whitespace
- for_where
- unused_enumerated
- trailing_whitespace
- switch_case_alignment
disabled_rules:
- weak_delegate
- redundant_optional_initialization
- class_delegate_protocol
- switch_case_on_newline
- let_var_whitespace
- array_init
- block_based_kvo
- trailing_closure
- multiple_closures_with_trailing_closure
- contains_over_first_not_nil
- discouraged_direct_init
- explicit_enum_raw_value
- fallthrough
- no_fallthrough_only
- is_disjoint
- joined_default_parameter
- literal_expression_end_indentation
- multiline_parameters
- no_grouping_extension
- pattern_matching_keywords
- private_over_fileprivate
- quick_discouraged_call
- single_test_class
- strict_fileprivate
- superfluous_disable_command
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- xctfail_message
- empty_enum_arguments
- notification_center_detachment
- unused_optional_binding
- operator_usage_whitespace
- closure_parameter_position
- closure_end_indentation
- unused_closure_parameter
- file_length
- control_statement
- closure_spacing
- conditional_returns_on_newline
- custom_rules
- explicit_init
- function_parameter_count
- overridden_super_call
- nesting
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- private_outlet
- private_unit_test
- type_name
- identifier_name
- valid_ibinspectable
- type_body_length
- syntactic_sugar
- large_tuple
force_cast: warning
control_statement: error
cyclomatic_complexity:
- 65
- 70
file_length: 2000
function_body_length: 600
line_length: 300
included: 
